param(
    [string]$ConfigPath,
    [string]$CacheRoot,
    [string]$OutputJson,
    [string]$OutputMarkdown,
    [int]$TopPerQuery = 0,
    [int]$PapersPerDirection = 20,
    [int]$CandidateFileLimit = 0,
    [switch]$AnalyzeOnly
)

$ErrorActionPreference = "Stop"

function Get-RepoRoot {
    return (Split-Path -Parent $PSScriptRoot)
}

function Read-JsonFile {
    param([string]$Path)
    return Get-Content -LiteralPath $Path -Raw -Encoding UTF8 | ConvertFrom-Json
}

function ConvertTo-Slug {
    param([string]$Text)
    $slug = ([regex]::Replace($Text.ToLowerInvariant(), "[^a-z0-9]+", "-")).Trim("-")
    if (-not $slug) { $slug = "query" }
    return $slug
}

function Get-Array {
    param($Value)
    if ($null -eq $Value) { return @() }
    if ($Value -is [System.Array]) { return @($Value) }
    return @($Value)
}

function Get-Field {
    param($Object, [string]$Name)
    if ($null -eq $Object) { return $null }
    if ($Object -is [System.Collections.IDictionary]) {
        return $Object[$Name]
    }
    return $Object.$Name
}

function Invoke-JsonScript {
    param([string]$ScriptPath, [hashtable]$Parameters)

    $output = & $ScriptPath @Parameters
    return ($output | ConvertFrom-Json)
}

function New-MarkdownReport {
    param($Config, $Profiles)

    $profileDirections = Get-Field -Object $Profiles -Name "directions"
    $lines = New-Object System.Collections.Generic.List[string]
    $lines.Add("# Common Research Direction Evidence Strength")
    $lines.Add("")
    $lines.Add('This file is generated by `scripts/Build-CommonPowerLitEvidenceProfiles.ps1` from `evaluation/common-research-directions.json` and local PowerLit subsets under `.cache/powerlit-subsets/common-directions`.')
    $lines.Add("")
    $targetPapers = Get-Field -Object $Profiles -Name "papers_per_direction_target"
    $lines.Add("Use it as a fast direction-level evidence bar before drafting, repairing, or reviewing recurring papers. The current target is $targetPapers reference papers per direction. It is not a final novelty search; widen back to the full PowerLit corpus before final literature claims.")
    $lines.Add("")
    $lines.Add("## Direction Summary")
    $lines.Add("")
    $lines.Add("| Direction | Project dirs | Queries | Sampled papers | Systems | Baselines | Metrics | Sensitivity | Reproducibility | Boundary |")
    $lines.Add("|---|---:|---:|---:|---:|---:|---:|---:|---:|---:|")

    foreach ($profile in $profileDirections) {
        $coverage = Get-Field -Object $profile -Name "aggregate_coverage"
        $summaryLabel = Get-Field -Object $profile -Name "label"
        $summaryDirCount = Get-Field -Object $profile -Name "project_dir_count"
        $summaryQueryCount = Get-Field -Object $profile -Name "query_count"
        $summarySampledCount = Get-Field -Object $profile -Name "sampled_paper_count"
        $lines.Add("| $summaryLabel | $summaryDirCount | $summaryQueryCount | $summarySampledCount | $($coverage.systems) | $($coverage.baselines) | $($coverage.metrics) | $($coverage.sensitivity) | $($coverage.reproducibility) | $($coverage.boundary) |")
    }

    foreach ($profile in $profileDirections) {
        $profileId = Get-Field -Object $profile -Name "id"
        $profileLabel = Get-Field -Object $profile -Name "label"
        $profileScope = Get-Field -Object $profile -Name "scope"
        $profileDirs = Get-Field -Object $profile -Name "mapped_research_dirs"
        $profileVenues = Get-Field -Object $profile -Name "target_venues"
        $profileSubsetRoot = Get-Field -Object $profile -Name "local_subset_root"
        $profileEvidenceBar = Get-Field -Object $profile -Name "evidence_bar"
        $profileQueryProfiles = Get-Field -Object $profile -Name "query_profiles"
        $lines.Add("")
        $lines.Add("## $profileLabel")
        $lines.Add("")
        $lines.Add("- ``id``: ``$profileId``")
        $lines.Add("- Scope: $profileScope")
        $lines.Add("- Project dirs: $((Get-Array -Value $profileDirs) -join '; ')")
        $lines.Add("- Target venues: $((Get-Array -Value $profileVenues) -join ', ')")
        $lines.Add("- Local subset root: ``$profileSubsetRoot``")
        $lines.Add("")
        $lines.Add("### Evidence Bar")
        foreach ($item in (Get-Array -Value $profileEvidenceBar.minimum_for_full_paper_8_9)) {
            $lines.Add("- $item")
        }
        if ($profileEvidenceBar.extra_gate_for_inverse_or_diagnostic_claims) {
            $lines.Add("")
            $lines.Add("Extra gate for inverse or diagnostic claims:")
            foreach ($item in (Get-Array -Value $profileEvidenceBar.extra_gate_for_inverse_or_diagnostic_claims)) {
                $lines.Add("- $item")
            }
        }
        $lines.Add("")
        $lines.Add("Blockers:")
        foreach ($item in (Get-Array -Value $profileEvidenceBar.blockers)) {
            $lines.Add("- $item")
        }
        $lines.Add("")
        $lines.Add("### PowerLit Profile")
        $lines.Add("")
        $lines.Add("| Query | Copied | Sampled | Systems | Baselines | Metrics | Sensitivity | Reproducibility | Boundary | Subset |")
        $lines.Add("|---|---:|---:|---:|---:|---:|---:|---:|---:|---|")
        foreach ($queryProfile in $profileQueryProfiles) {
            $coverage = $queryProfile.analysis.coverage_in_sample
            $copied = if ($queryProfile.subset.copied_count -ne $null) { $queryProfile.subset.copied_count } else { 0 }
            $sampled = if ($queryProfile.analysis.sampled_paper_count -ne $null) { $queryProfile.analysis.sampled_paper_count } else { 0 }
            $subsetPath = if ($queryProfile.subset.destination) { $queryProfile.subset.destination } else { $queryProfile.destination }
            $lines.Add("| $($queryProfile.id) | $copied | $sampled | $($coverage.systems) | $($coverage.baselines) | $($coverage.metrics) | $($coverage.sensitivity) | $($coverage.reproducibility) | $($coverage.boundary) | ``$subsetPath`` |")
        }
        $lines.Add("")
        $lines.Add("Reference papers sampled:")
        foreach ($queryProfile in $profileQueryProfiles) {
            foreach ($paper in (Get-Array -Value $queryProfile.analysis.papers)) {
                $venue = if ($paper.source_title) { $paper.source_title } else { "unknown venue" }
                $doi = if ($paper.doi) { " DOI: $($paper.doi)" } else { "" }
                $lines.Add("- $($queryProfile.id): $($paper.title) ($venue).$doi")
            }
        }
    }

    return ($lines -join [Environment]::NewLine)
}

$repoRoot = Get-RepoRoot
if (-not $ConfigPath) {
    $ConfigPath = Join-Path $repoRoot "evaluation\common-research-directions.json"
}
if (-not $CacheRoot) {
    $CacheRoot = Join-Path $repoRoot ".cache\powerlit-subsets\common-directions"
}
if (-not $OutputJson) {
    $OutputJson = Join-Path $repoRoot "evaluation\common-research-direction-evidence-strength.json"
}
if (-not $OutputMarkdown) {
    $OutputMarkdown = Join-Path $repoRoot "evaluation\common-research-direction-evidence-strength.md"
}

$config = Read-JsonFile -Path $ConfigPath
$builder = Join-Path $repoRoot "skills\powerlit-power-systems-literature-intelligence\scripts\Build-PowerLitLocalSubset.ps1"
$analyzer = Join-Path $repoRoot "skills\powerlit-power-systems-literature-intelligence\scripts\Analyze-PowerLitEvidenceStrength.ps1"

if (-not (Test-Path -LiteralPath $builder)) {
    throw "Missing local subset builder: $builder"
}
if (-not (Test-Path -LiteralPath $analyzer)) {
    throw "Missing evidence analyzer: $analyzer"
}

New-Item -ItemType Directory -Force -Path $CacheRoot | Out-Null
New-Item -ItemType Directory -Force -Path (Split-Path -Parent $OutputJson) | Out-Null

$directionProfiles = New-Object System.Collections.Generic.List[object]
foreach ($direction in $config.directions) {
    $directionCacheRoot = Join-Path $CacheRoot $direction.id
    New-Item -ItemType Directory -Force -Path $directionCacheRoot | Out-Null
    $queryProfiles = New-Object System.Collections.Generic.List[object]
    $aggregate = [ordered]@{
        systems = 0
        baselines = 0
        metrics = 0
        sensitivity = 0
        reproducibility = 0
        boundary = 0
    }
    $sampledTotal = 0
    $directionQueries = @(Get-Array -Value $direction.queries)
    $queryCountForTarget = [Math]::Max($directionQueries.Count, 1)
    $targetTopPerQuery = [int][Math]::Ceiling($PapersPerDirection / $queryCountForTarget)

    foreach ($querySpec in $directionQueries) {
        $queryTop = if ($TopPerQuery -gt 0) { $TopPerQuery } elseif ($PapersPerDirection -gt 0) { $targetTopPerQuery } else { [int]$querySpec.top }
        if ($queryTop -le 0) { $queryTop = 8 }
        $queryLimit = if ($CandidateFileLimit -gt 0) { $CandidateFileLimit } else { [int]$querySpec.candidate_file_limit }
        if ($queryLimit -le 0) { $queryLimit = 350 }
        $queryId = if ($querySpec.id) { [string]$querySpec.id } else { ConvertTo-Slug -Text $querySpec.query }
        $destination = Join-Path $directionCacheRoot $queryId
        $venueFolders = @(Get-Array -Value $querySpec.venue_folders)
        $terms = @(Get-Array -Value $querySpec.terms)
        $scriptTerms = @($terms | Where-Object { $_ })

        $subset = [pscustomobject]@{
            available = $false
            destination = $destination
            copied_count = 0
            message = "AnalyzeOnly"
        }
        $manifestPath = Join-Path $destination "powerlit_subset_manifest.json"
        if ($AnalyzeOnly -and (Test-Path -LiteralPath $manifestPath)) {
            $subset = Read-JsonFile -Path $manifestPath
        } elseif (-not $AnalyzeOnly) {
            $builderParams = @{
                Query = [string]$querySpec.query
                Top = $queryTop
                CandidateFileLimit = $queryLimit
                Destination = $destination
            }
            if ($scriptTerms.Count -gt 0) {
                $builderParams.Terms = [string[]]$scriptTerms
            }
            if ($venueFolders.Count -gt 0) {
                $builderParams.VenueFolder = [string[]]$venueFolders
            }
            $subset = Invoke-JsonScript -ScriptPath $builder -Parameters $builderParams
        }

        $analysisParams = @{
            PowerLitJsonRoot = $destination
            Query = [string]$querySpec.query
            Top = $queryTop
            CandidateFileLimit = [Math]::Max($queryTop * 4, 20)
        }
        if ($scriptTerms.Count -gt 0) {
            $analysisParams.Terms = [string[]]$scriptTerms
        }
        if ($venueFolders.Count -gt 0) {
            $analysisParams.VenueFolder = [string[]]$venueFolders
        }
        $analysis = Invoke-JsonScript -ScriptPath $analyzer -Parameters $analysisParams

        foreach ($key in @($aggregate.Keys)) {
            if ($analysis.coverage_in_sample.$key -ne $null) {
                $aggregate[$key] += [int]$analysis.coverage_in_sample.$key
            }
        }
        if ($analysis.sampled_paper_count -ne $null) {
            $sampledTotal += [int]$analysis.sampled_paper_count
        }

        $queryProfiles.Add([pscustomobject]@{
            id = $queryId
            query = $querySpec.query
            terms = $terms
            venue_folders = $venueFolders
            destination = $destination
            subset = $subset
            analysis = $analysis
        })
    }

    $mappedDirs = @(Get-Array -Value $direction.mapped_research_dirs)
    $claimClasses = @(Get-Array -Value $direction.claim_classes)
    $targetVenues = @(Get-Array -Value $direction.target_venues)
    $directionProfile = @{}
    $directionProfile["id"] = $direction.id
    $directionProfile["label"] = $direction.label
    $directionProfile["scope"] = $direction.scope
    $directionProfile["cross_cutting"] = $direction.cross_cutting
    $directionProfile["mapped_research_dirs"] = $mappedDirs
    $directionProfile["project_dir_count"] = $mappedDirs.Count
    $directionProfile["claim_classes"] = $claimClasses
    $directionProfile["target_venues"] = $targetVenues
    $directionProfile["evidence_bar"] = $direction.evidence_bar
    $directionProfile["local_subset_root"] = $directionCacheRoot
    $directionProfile["query_count"] = $queryProfiles.Count
    $directionProfile["sampled_paper_count"] = $sampledTotal
    $directionProfile["aggregate_coverage"] = [pscustomobject]$aggregate
    $directionProfile["query_profiles"] = $queryProfiles.ToArray()
    $directionProfiles.Add($directionProfile)
}

$profiles = @{
    schema_version = 1
    created_at = (Get-Date).ToString("o")
    config_path = $ConfigPath
    source_rule = $config.source_rule
    local_subset_root = $CacheRoot
    papers_per_direction_target = $PapersPerDirection
    directions = $directionProfiles.ToArray()
}

$profiles | ConvertTo-Json -Depth 20 | Set-Content -LiteralPath $OutputJson -Encoding UTF8
$markdown = New-MarkdownReport -Config $config -Profiles $profiles
$markdown | Set-Content -LiteralPath $OutputMarkdown -Encoding UTF8

$result = @{
    ok = $true
    direction_count = $directionProfiles.Count
    profile_json = $OutputJson
    profile_markdown = $OutputMarkdown
    local_subset_root = $CacheRoot
}
$result | ConvertTo-Json -Depth 6
